services:
  mysql-legacy:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '${MYSQL_PORT_LEGACY}:3306'
    volumes:
      - database-volume-legacy:/var/lib/mysql

  nginx:
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./docker/${ENV}/nginx/website.conf:/etc/nginx/conf.d/default.conf:ro
      - ./apps/website:/apps/website
    environment:
      - LOCAL_NGINX_PORT=8080
    ports:
      - '${NGINX_PORT}:8080'
    depends_on:
      - website-php

  website-php:
    build:
      context: .
      dockerfile: docker/${ENV}/php/website/Dockerfile
    volumes:
      - ./apps/website:/apps/website
    restart: on-failure
    env_file:
      - .env
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    user: ${LOCAL_USER}

volumes:
  database-volume-legacy:
