services:
  mysql:
    image: mysql:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - database-volume:/var/lib/mysql

  nginx-rewrite:
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./docker/${ENV}/nginx/website-rewrite.conf:/etc/nginx/conf.d/default.conf:ro
      - ./apps/website-rewrite:/apps/website-rewrite
    ports:
      - '${NGINX_REWRITE_PORT}:80'
      - '${NGINX_REWRITE_REPORT_PORT}:81'
    depends_on:
      - website-rewrite-php

  website-rewrite-php:
    build:
      context: .
      dockerfile: docker/${ENV}/php/website-rewrite/Dockerfile
    volumes:
      - ./apps/website-rewrite:/apps/website-rewrite
    restart: on-failure
    env_file:
      - .env
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      XDEBUG_MODE: coverage
    user: ${LOCAL_USER}

  blackfire:
    image: blackfire/blackfire:2
    ports: ["8307"]
    environment:
      BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
      BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
      BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
      BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}

volumes:
  database-volume:
